<a href="https://colab.research.google.com/github/killer-knight/CCMS-F/blob/main/Colab_Numpy_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
my_list=[1,2,3]


In [3]:
arr=np.array(my_list)
arr


array([1, 2, 3])

In [4]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.ones(4)

array([1., 1., 1., 1.])

In [13]:
# np.zeros(3)
# # np.zeros((2,3))
# np.ones(4)
# np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
# np.random.rand(5)
# np.random.rand(2,3)
np.random.randn(2)

array([-0.34938613,  0.67991274])

In [21]:
np.random.randn(3,3)

array([[ 1.14741213, -1.25097847, -0.1229062 ],
       [-0.98719806,  0.07323487, -0.12773502],
       [ 0.33541048,  1.3689871 ,  1.50550368]])

In [24]:
# np.random.randint(1,100,10)
np.random.randint(1,100)

94

In [28]:
# arr=np.arange(25)
# arr
ranarr=np.random.randint(0,50,10)
ranarr


array([ 9, 30, 31, 16,  2, 18, 13, 26, 16, 39])

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
# arr.reshape(5,10)
# ranarr.max()
# ranarr.min()

2

In [34]:
# ranarr.argmax()
ranarr.argmin()

4

In [37]:
arr=arr.reshape(5,5)
arr.shape


(5, 5)

In [38]:
arr.dtype

dtype('int64')

In [40]:
from numpy.random import randint
# randint(2,10)

8